version: '2'

services:
    devcoffee:
        build: .
        image: devcoffee:latest
        ports:
            - "80:3000"
        volumes:
            - "./data:/app/data"
        env_file: .env
